### ISSUE TITLE
ossimcik rolu çalıştırılırken conf_list hatası

### ISSUE THREAD

**Issue by selinakbuga** [Pardus-Ahtapot/MYS#105]
ossimcik playbooku çalışırken ekteki hatayı vermektedir.

TASK [ossimcik : playbook rolleri ediniliyor] **********************************
fatal: [collector.ahtapot.org.tr -> localhost]: FAILED! => {"changed": true, "cmd": "/usr/bin/python /etc/ansible/roles/ossimcik/files/get_playbook_conf_lists.py", "delta": "0:00:00.213306", "end": "2021-02-01 13:44:14.100823", "failed": true, "rc": 1, "start": "2021-02-01 13:44:13.887517", "stderr": "Traceback (most recent call last):\n  File \"/etc/ansible/roles/ossimcik/files/get_playbook_conf_lists.py\", line 47, in <module>\n    main()\n  File \"/etc/ansible/roles/ossimcik/files/get_playbook_conf_lists.py\", line 38, in main\n    playbook_roles[playbook_name] = playbook_roles[playbook_name] + content[\"{}_conf_list\".format(role[\"role\"].replace(\"-\", \"_\"))]\nKeyError: 'gitlab_container_conf_list'", "stdout": "", "stdout_lines": [], "warnings": []}

<img width="1679" alt="Ekran Resmi 2021-02-01 14 00 37" src="https://user-images.githubusercontent.com/15850677/106451004-ff896b00-6496-11eb-82f9-eacc6b0a496e.png">

**Comment by selinakbuga** [comment]
roles/gitlab-container/vars içerisindeki conf_list yml dosyasında kök node gitlab_conf_list olarak belirtilmiş. gitlab_container_conf_list anahtarı aranmaktadır.

**Comment by ciari** [comment]
fixed in #106
