### ISSUE TITLE
update-ahtapot.py bug

### ISSUE THREAD

**Issue by zkryakgul** [Pardus-Ahtapot/MYS#73]
### Tanım:
update-ahtapot.py yeni girilen firewall kurallarını gerekli firewallar'a iletmesi için yazılmış python scriptidir.

### Bug açıklaması:
script'in çalıştırdığı playbook oynama sırasında bir hata meydana gelirse git üzerinden değişiklik kontrolü yaparak yeni kuralların gönderilmesine karar verildiğinden; yani bir kural girilene veya bir kural değiştirilene kadar mevcut kurallar uygulanamıyor.

### Önerilen çözüm
script çalışması sırasında ansible komutunun geri dönüşü kontrol edilerek fail olması durumunda tetikleme için kullanılan "firewall" dosyası ile aynı path üzerinde "firewall.retry" isimli bir dosya oluşturularak script içerisinde kontrol edilir ve tekrar denenmesi için playbook tekrar çalıştırılır.

**Comment by ciari** [comment]
ansbible.cfg => retry_files_save_path düzenlenerek çözülebilir.
