### ISSUE TITLE
Firewallbuilder playbook'u çalışması sırasında git modulü hata vermektedir

### ISSUE THREAD

**Issue by zkryakgul** [Pardus-Ahtapot/MYS#84]
Firewallbuilder playbook'u çalıştırılması sırasında aşağıdaki hata oluşmaktadır. 

```
TASK [firewallbuilder : Git depolari olusturuluyor.] ***************************
failed: [AH06005fwb.zek.local.ahtapot] (item={'key': u'repo01', 'value': {u'repo': u'ssh://git@ah06002git.zek.local.ahtapot:33433/ahtapotops/gdys.git', u'key_file': u'/home/ahtapotops/.ssh/id_rsa', u'destination': u'/etc/fw/gdys', u'accept_hostkey': u'yes'}}) => {"failed": true, "item": {"key": "repo01", "value": {"accept_hostkey": "yes", "destination": "/etc/fw/gdys", "key_file": "/home/ahtapotops/.ssh/id_rsa", "repo": "ssh://git@ah06002git.zek.local.ahtapot:33433/ahtapotops/gdys.git"}}, "msg": "failed to get the hostkey for ah06002git.zek.local.ahtapot"}
```

Hata araştırıldığında ansible sürümünde bulunan bir bug'dan ötürü kaynaklandığı anlaşılmaktadır

Bkz. https://github.com/ansible/ansible/issues/24860

Bu bug'un ileriki sürümlerde fixlendiği görülmüştür. 
Hatayı gideren PR: https://github.com/ansible/ansible/pull/26072

Bu durumda bazı kurulumlarda karşılaşılan bu hatanın çözümü için Ansible sürümü 2.2.3.0 a yükseltilebilir veya mevcut sürüm PR'daki değişiklikleri içerecek şekilde patchlenebilir.

**Comment by ciari** [comment]
known_hosts dosyası ile ilgili bir soruna benziyor. SSH keyleri dağıtırken, hostname mi IP adresi mi kullanıyorsun dikkat eder misin? ve key dağıttıktan sonra mutlaka en az bir defa ssh ile bağlanarak fingerprint kaydedildiğinden emin olur musun

**Comment by zkryakgul** [comment]
SSH keylerini dağıtırken hostname kullanıyorum. İlgili git makinesine ait known_hosts içerisindeki kaydı temizleyip tekrardan FQDN aracılığı ile ssh atarak fingerprint kaydedilmesi sorusuna yes dememe rağmen aşağıdaki komut ile sorgulama yaptığımda ilgili FQDN'e ait herhangi bir kayıt bulunamıyor.
```
$ ssh-keygen -H -F ah06002git.zek.local.ahtapot
$ ssh-keygen -H -F AH06002git.zek.local.ahtapot
```

Ancak ssh ile bağlantı sırasında aşağıdaki komut ile HostKeyAlias atarsam yukarıdaki komutlardan olumlu çıktı alabiliyorum:
```
ssh -o HostKeyAlias=AH06002git.zek.local.ahtapot AH06002git.zek.local.ahtapot -p33433
```
